name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: PSR94
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-light&color_snake=%23059669&color_dots=%23e0f2fe,%23bae6fd,%237dd3fc,%238b5cf6,%2307111f
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=%2334d399&color_dots=%2307111f,%230c4a6e,%230284c7,%238b5cf6,%23e2e8f0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish generated files
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
          force_orphan: true
